FROM mcr.microsoft.com/dotnet/runtime:5.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["Net5Server/Net5Server.csproj", "Net5Server/"]
RUN dotnet restore "Net5Server/Net5Server.csproj"
COPY . .
WORKDIR "/src/Net5Server"
RUN dotnet build "Net5Server.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Net5Server.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Net5Server.dll"]
